engine_config:
  dtype: half
  max_model_len: 2048
  model: /root/.cache/huggingface/hub/models--unsloth--Meta-Llama-3.1-70B-Instruct
extra_envs:
- name: HF_TOKEN
extra_labels:
  model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
  openllm_alias: 8b,8b-instruct
project: vllm-chat
service_config:
  name: llama3.1
  resources:
    gpu: 8
    gpu_type: nvidia-rtx-3060
  traffic:
    timeout: 300
