engine_config:
  max_model_len: 131072
  model: unsloth/Meta-Llama-3.1-70B-Instruct
  tensor_parallel_size: 2
extra_envs:
- name: HF_TOKEN
extra_labels:
  model_name: unsloth/Meta-Llama-3.1-70B-Instruct
  openllm_alias: 70b,70b-instruct
project: vllm-chat
service_config:
  name: llama3.1
  resources:
    gpu: 8
    gpu_type: nvidia-rtx-3060
  traffic:
    timeout: 60000
